CREATE TABLE `sap-reservation-document-item`
(
    `Reservation`           int(10) DEFAULT NULL,
    `ReservationItem`       int(4) DEFAULT NULL,
    `RecordType`            varchar(1) DEFAULT NULL,
    `Product`               varchar(40) DEFAULT NULL,
    `RequirementType`       varchar(2) DEFAULT NULL,
    `MatlCompRequirementDate` date DEFAULT NULL,
    `Plant`                 varchar(4) DEFAULT NULL,
    `ManufacturingOrderOperation` int(10) DEFAULT NULL,
    `GoodsMovementIsAllowed` varchar(1) DEFAULT NULL,
    `StorageLocation`       varchar(4) DEFAULT NULL,
    `Batch`                 varchar(10) DEFAULT NULL,
    `DebitCreditCode`       varchar(1) DEFAULT NULL,
    `BaseUnit`              varchar(3) DEFAULT NULL,
    `GLAccount`             varchar(10) DEFAULT NULL,
    `GoodsMovementType`     varchar(3) DEFAULT NULL,
    `EntryUnit`             varchar(3) DEFAULT NULL,
    `QuantityIsFixed`       varchar(1) DEFAULT NULL,
    `CompanyCodeCurrency`   varchar(5) DEFAULT NULL,
    `IssuingOrReceivingPlant` varchar(4) DEFAULT NULL,
    `IssuingOrReceivingStorageLoc` varchar(4) DEFAULT NULL,
    `PurchasingDocument`    varchar(10) DEFAULT NULL,
    `PurchasingDocumentItem` int(5) DEFAULT NULL,
    `Supplier`              varchar(10) DEFAULT NULL,
    `ResvnItmRequiredQtyInBaseUnit` float(13) DEFAULT NULL,
    `ReservationItemIsFinallyIssued` varchar(1) DEFAULT NULL,
    `ReservationItmIsMarkedForDeltn` varchar(1) DEFAULT NULL,
    `ResvnItmRequiredQtyInEntryUnit` float(13) DEFAULT NULL,
    `ResvnItmWithdrawnQtyInBaseUnit` float(13) DEFAULT NULL,
    `ResvnItmWithdrawnAmtInCCCrcy` float(11) DEFAULT NULL,
    `GoodsRecipientName`    varchar(12) DEFAULT NULL,
    `UnloadingPointName`    varchar(25) DEFAULT NULL,
    `ReservationItemText`   varchar(50) DEFAULT NULL,
    PRIMARY KEY (`Reservation`, `ReservationItem`),
    CONSTRAINT `Reservation_fk` FOREIGN KEY (`Reservation`) REFERENCES `sap-reservation-document-header` (`Reservation`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
